import React, { Component } from "react";

export default class Maps extends Component {
  render() {
    return (
      <div className="container-fluid row jossa text-justify">
      

<table align="center"  cellpadding="1" cellspacing="1"  ><tbody><tr><th><p><strong>National Institutes of Technology (NITs)</strong></p></th><th><p><strong>Indian Institutes of Information Technology (IIITs, IIITM &amp; IIITDM)</strong></p></th><th><p><strong>Other Central Government/State Government Funded Institutions</strong></p></th></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-agartala"  target="_blank"
                rel="noreferrer">National Institute of Technology, Agartala (Tripura)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iitm-gwalior"  target="_blank"
                rel="noreferrer">Atal Bihari Vajpayee Indian Institute of Information Technology &amp; Management, Gwalior</a></strong></p><p><strong><a href="https://www.collegedekho.com/colleges/iitm-gwalior"  target="_blank"
                rel="noreferrer">(M.P.)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/assam-university"  target="_blank"
                rel="noreferrer">Assam University, Silchar (Assam)</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/mnnit"  target="_blank"
                rel="noreferrer">Motilal Nehru National Institute of Technology, Allahabad (U.P.)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiitdm-kancheepuram"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology, Design &amp; Manufacturing, Kanchipuram, Chennai</a></strong></p><p><strong><a href="https://www.collegedekho.com/colleges/iiitdm-kancheepuram"  target="_blank"
                rel="noreferrer">(Tamil Nadu)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/bit-mesra"  target="_blank"
                rel="noreferrer">Birla Institute of Technology, Mesra, Ranchi (Jharkhand)</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-arunachal-pradesh"  target="_blank"
                rel="noreferrer">National Institute of Technology, Arunachal Pradesh.</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiita"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology, Jhalwa, Allahabad (UP)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/gkv-haridwar"  target="_blank"
                rel="noreferrer">Gurukul Kangri Vishwavidyalaya, Haridwar (Uttarakhand)</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/manit"  target="_blank"
                rel="noreferrer">Maulana Azad National Institute of Technology, Bhopal (MP)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/pdpmiiitdm"  target="_blank"
                rel="noreferrer">Pandit Dwarka Prasad Mishra Indian Institute of Information Technology, Design &amp;</a></strong></p><p><strong><a href="https://www.collegedekho.com/colleges/pdpmiiitdm"  target="_blank"
                rel="noreferrer">Manufacturing, Jabalpur, MP</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iict-bhadohi"  target="_blank"
                rel="noreferrer">Indian Institute of Carpet Technology, Bhadohi (U.P.)</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-calicut"  target="_blank"
                rel="noreferrer">National Institute of Technology, Calicut (Kerala)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-guwahati"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology, Guwahati (Assam)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/institute-of-infrastructure-technology-research-and-management-ahmedabad"  target="_blank"
                rel="noreferrer">Institute of Infrastructure, Technology, Research &amp; Management, Ahmadabad</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-delhi"  target="_blank"
                rel="noreferrer">National Institute of Technology, Delhi</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-kota"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology, Kota (Rajasthan)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/institute-of-technology-bilaspur"  target="_blank"
                rel="noreferrer">Institute of Technology, Guru Ghasidas Vishawavidyalaya, Bilaspur (C.G.)</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-durgapur"  target="_blank"
                rel="noreferrer">National Institute of Technology, Durgapur (West Bengal)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-sri-city"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology, Sri City, Chitoor (A. P.)</a></strong></p></td><td><p><strong>J.K. Institute of Applied Physics &amp; Technology, University of Allahabad, Allahabad- 211002</strong></p><p><strong>(U.P.)</strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-goa"  target="_blank"
                rel="noreferrer">National Institute of Technology, Goa</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-vadodara"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology, Vadodara (Gujarat)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/mizoram-university"  target="_blank"
                rel="noreferrer">Mizoram University, Aizwal-796009</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-hamirpur"  target="_blank"
                rel="noreferrer">National Institute of Technology, Hamirpur (Himachal Pradesh)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-manipur"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology Manipur Mantripukhri, Imphal 795001</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/national-institute-of-foundry-forge-technology-hatia-ranchi"  target="_blank"
                rel="noreferrer">National Institute of Foundry &amp; Forge Technology, P.O. Hatia, Ranchi (Jharkhand).</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/mnit-jaipur"  target="_blank"
                rel="noreferrer">Malviya National Institute of Technology, Jaipur (Rajasthan)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-srirangam"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology Srirangam, Tiruchirappalli</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/spa-bhopal"  target="_blank"
                rel="noreferrer">School of Planning and Architecture, Bhopal (Madhya Pradesh)</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-jalandhar"  target="_blank"
                rel="noreferrer">Dr. B R Ambedkar National Institute of Technology, Jalandhar (Punjab)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-lucknow"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology Lucknow</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/spa-delhi"  target="_blank"
                rel="noreferrer">School of Planning and Architecture, I.P. Estate, New Delhi (SPA, Delhi).</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-jamshedpur"  target="_blank"
                rel="noreferrer">National Institute of Technology, Jamshedpur (Jharkhand)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-dharwad"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology (IIIT) Dharwad</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/spa-vijayawada"  target="_blank"
                rel="noreferrer">School of Planning and Architecture, Vijayawada (Andhra Pradesh)</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-kurukshetra"  target="_blank"
                rel="noreferrer">National Institute of Technology, Kurukshetra (Haryana)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiitdm"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology (IIIT) Kurnool</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/shri-mata-vaishno-devi-university"  target="_blank"
                rel="noreferrer">Shri Mata Vaishno Devi University, Katra-182320 (J &amp; K)</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-manipur"  target="_blank"
                rel="noreferrer">National Institute of Technology, Manipur</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/indian-institute-of-information-technology-kottayam"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology (IIIT) Kottayam</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/tezpur-university"  target="_blank"
                rel="noreferrer">Tezpur University, NAPAAM, Tezpur (Assam</a>)</strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-meghalaya"  target="_blank"
                rel="noreferrer">National Institute of Technology, Meghalaya</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-kalyani"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology (IIIT) Kalyani, West Bengal</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiest"  target="_blank"
                rel="noreferrer">Indian Institute of Engineering Science &amp; Technology, Shibpur, Distt Howrah (Formerly</a></strong></p><p><strong><a href="https://www.collegedekho.com/colleges/iiest"  target="_blank"
                rel="noreferrer">Bengal Engineering &amp; Science University Shibpur)</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-mizoram"  target="_blank"
                rel="noreferrer">National Institute of Technology, Mizoram</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-sonepat"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology (IIIT) Kilohrad, Sonepat, Haryana</a></strong></p></td><td><p><strong>Indian Institute of Crop Processing Technology, Thanjavur, Tamil Nadu</strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-nagaland"  target="_blank"
                rel="noreferrer">National Institute of Technology, Nagaland</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-una"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology (IIIT) Una, Himachal Pradesh</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/nielit-aurangabad"  target="_blank"
                rel="noreferrer">National Institute of Electronics and Information Technology, Aurangabad, Maharashtra</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/vnit"  target="_blank"
                rel="noreferrer">Visvesvaraya National Institute of Technology, Nagpur (Maharashtra)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/indian-institute-of-information-technology-6"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology (IIIT) Ranchi, Jharkhand</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/sliet"  target="_blank"
                rel="noreferrer">SantLongowal Institute of Engineering and Technology Longowal – 148106, Distt. Sangrur</a></strong></p><p><strong><a href="https://www.collegedekho.com/colleges/sliet"  target="_blank"
                rel="noreferrer">(Pb.), India</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-patna"  target="_blank"
                rel="noreferrer">National Institute of Technology, Patna (Bihar)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/iiit-nagpur"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology (IIIT) Nagpur, Maharashtra</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/hbti"  target="_blank"
                rel="noreferrer">Harcourt Butler Technical University, Kanpur (U.P.)</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-puducherry"  target="_blank"
                rel="noreferrer">National Institute of Technology, Puducherry</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/indian-institute-of-information-technology-pune"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology (IIIT) Pune, Maharashtra</a></strong></p></td><td><p><strong>Indian Institute of Petroleum &amp; Energy, Visakhapatnam.</strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-raipur"  target="_blank"
                rel="noreferrer">National Institute of Technology, Raipur (Chhattisgarh)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/indian-institute-of-information-technology-bhagalpur"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology Bhagalpur</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/indian-institute-of-handloom-technologytamil-nadu"  target="_blank"
                rel="noreferrer">Indian Institute of Handloom Technology, Salem, Tamil Nadu.</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/national-institute-of-technology-rourkela"  target="_blank"
                rel="noreferrer">National Institute of Technology, Rourkela (Odisha)</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/indian-institute-of-information-technology-bhopal"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology Bhopal</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/jamia-hamdard"  target="_blank"
                rel="noreferrer">Jamia Hamdard University, Delhi.</a></strong></p></td></tr><tr><td><p><strong>National Institute of Technology, Sikkim</strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/indian-institute-of-information-technology-surat"  target="_blank"
                rel="noreferrer">Indian Institute of Information Technology Surat</a></strong></p></td><td><p><strong><a href="https://www.collegedekho.com/colleges/university-of-hyderabad"  target="_blank"
                rel="noreferrer">University of Hyderabad, Hyderabad.</a></strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-silchar"  target="_blank"
                rel="noreferrer">National Institute of Technology, Silchar (Assam)</a></strong></p></td><td><p><strong>--</strong></p></td><td><p><strong>--</strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-srinagar"  target="_blank"
                rel="noreferrer">National Institute of Technology, Hazartbal, Srinagar (J &amp; K)</a></strong></p></td><td><p><strong>--</strong></p></td><td><p><strong>--</strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/svnit"  target="_blank"
                rel="noreferrer">Sardar Vallabhbhai National Institute of Technology, Surat (Gujarat)</a></strong></p></td><td><p><strong>--</strong></p></td><td><p><strong>--</strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nitk"  target="_blank"
                rel="noreferrer">National Institute of Technology, Surathkal, Mangalore (Karnataka)</a></strong></p></td><td><p><strong>--</strong></p></td><td><p><strong>--</strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-trichy"  target="_blank"
                rel="noreferrer">National Institute of Technology, Tiruchirapalli (Tamil Nadu)</a></strong></p></td><td><p><strong>--</strong></p></td><td><p><strong>--</strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-uttrakhand"  target="_blank"
                rel="noreferrer">National Institute of Technology, Uttrakhand</a></strong></p></td><td><p><strong>--</strong></p></td><td><p><strong>--</strong></p></td></tr><tr><td><p><strong><a href="https://www.collegedekho.com/colleges/nit-warangal"  target="_blank"
                rel="noreferrer">National Institute of Technology, Warangal</a></strong></p></td><td><p><strong>--</strong></p></td><td><p><strong>--</strong></p></td></tr><tr><td><strong><a href="https://www.collegedekho.com/colleges/nova-institute-of-technology-eluru"  target="_blank"
                rel="noreferrer">National Institute of Technology, Andhra Pradesh, Vatluru, Eluru – 534007</a></strong></td><td>-</td><td>-</td></tr></tbody></table>


      </div>
    );
  }
}
